[package]
name = "ML_webserver_bench"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13.5"
tract = "0.21.7"
tract-onnx = "0.21.7"
clap = { version = "4.5.19", features = ["derive"] }
image = "0.25.2"
ort = { version = "2.0.0-rc.6"}
nalgebra = {version="0.33.0"}
ndarray = {version="0.16.1"}
anyhow = "1.0.89"
actix-web = "4.9.0"
actix-files = "0.6.6"
tch = "0.17.0"
serde = { version = "1.0.210", features = ["derive"] }


[[bin]]
name="demo_webserver"
path="src/webserver.rs"

[lib]
name="yolo_mulitbackend_demo"
path="src/lib.rs"


[profile.release]
opt-level = "z"
strip = true  # WE STRIPPING THE SYMBOLS WITH THIS ONE  ğŸ—£ï¸ğŸ—£ï¸ğŸ”¥ğŸ”¥ğŸ”¥
lto = true
